# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'paybox6.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import paybox_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 768)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-image: url(:/bckgrnd/bgnd500.png);")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1024, 768))
        self.i0mainPage = QWidget()
        self.i0mainPage.setObjectName(u"i0mainPage")
        self.i0frGetCoins = QFrame(self.i0mainPage)
        self.i0frGetCoins.setObjectName(u"i0frGetCoins")
        self.i0frGetCoins.setGeometry(QRect(0, 0, 371, 171))
        self.i0frGetCoins.setMinimumSize(QSize(371, 171))
        self.i0frGetCoins.setMaximumSize(QSize(371, 171))
        self.i0frGetCoins.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500getcoins.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500getcoinspressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}")
        self.i0frGetCoins.setFrameShape(QFrame.NoFrame)
        self.i0frGetCoins.setFrameShadow(QFrame.Plain)
        self.i0btnGetCoins = QPushButton(self.i0frGetCoins)
        self.i0btnGetCoins.setObjectName(u"i0btnGetCoins")
        self.i0btnGetCoins.setGeometry(QRect(10, 10, 160, 160))
        self.i0btnGetCoins.setFocusPolicy(Qt.NoFocus)
        self.i0btnGetCoins.setAutoRepeat(False)
        self.i0btnGetCoins.setFlat(True)
        self.i0lblGetCoins = QLabel(self.i0frGetCoins)
        self.i0lblGetCoins.setObjectName(u"i0lblGetCoins")
        self.i0lblGetCoins.setGeometry(QRect(180, 50, 181, 81))
        self.i0lblGetCoins.setMinimumSize(QSize(181, 81))
        self.i0lblGetCoins.setMaximumSize(QSize(181, 81))
        font = QFont()
        font.setFamily(u"Berlin Sans FB")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.i0lblGetCoins.setFont(font)
        self.i0lblGetCoins.setWordWrap(True)
        self.i0frNewCard = QFrame(self.i0mainPage)
        self.i0frNewCard.setObjectName(u"i0frNewCard")
        self.i0frNewCard.setGeometry(QRect(0, 350, 471, 181))
        self.i0frNewCard.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}")
        self.i0frNewCard.setFrameShape(QFrame.NoFrame)
        self.i0frNewCard.setFrameShadow(QFrame.Plain)
        self.i0btnNewCard = QPushButton(self.i0frNewCard)
        self.i0btnNewCard.setObjectName(u"i0btnNewCard")
        self.i0btnNewCard.setGeometry(QRect(10, 10, 160, 160))
        font1 = QFont()
        font1.setFamily(u"Berlin Sans FB")
        font1.setPointSize(18)
        font1.setBold(False)
        font1.setWeight(50)
        self.i0btnNewCard.setFont(font1)
        self.i0btnNewCard.setFocusPolicy(Qt.NoFocus)
        self.i0btnNewCard.setAutoRepeat(False)
        self.i0btnNewCard.setFlat(True)
        self.i0lblNewCard = QLabel(self.i0frNewCard)
        self.i0lblNewCard.setObjectName(u"i0lblNewCard")
        self.i0lblNewCard.setGeometry(QRect(180, 50, 281, 81))
        self.i0lblNewCard.setFont(font)
        self.i0lblNewCard.setWordWrap(True)
        self.i0frRechargeCard = QFrame(self.i0mainPage)
        self.i0frRechargeCard.setObjectName(u"i0frRechargeCard")
        self.i0frRechargeCard.setGeometry(QRect(0, 170, 471, 181))
        self.i0frRechargeCard.setMinimumSize(QSize(471, 181))
        self.i0frRechargeCard.setMaximumSize(QSize(471, 181))
        self.i0frRechargeCard.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500rechargecard.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500rechargecardpressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}")
        self.i0frRechargeCard.setFrameShape(QFrame.NoFrame)
        self.i0frRechargeCard.setFrameShadow(QFrame.Plain)
        self.i0btnRechargeCard = QPushButton(self.i0frRechargeCard)
        self.i0btnRechargeCard.setObjectName(u"i0btnRechargeCard")
        self.i0btnRechargeCard.setGeometry(QRect(10, 10, 160, 160))
        self.i0btnRechargeCard.setFocusPolicy(Qt.NoFocus)
        self.i0btnRechargeCard.setAutoRepeat(False)
        self.i0btnRechargeCard.setFlat(True)
        self.i0lblRechargeCard = QLabel(self.i0frRechargeCard)
        self.i0lblRechargeCard.setObjectName(u"i0lblRechargeCard")
        self.i0lblRechargeCard.setGeometry(QRect(180, 50, 281, 81))
        self.i0lblRechargeCard.setMinimumSize(QSize(281, 81))
        self.i0lblRechargeCard.setMaximumSize(QSize(281, 81))
        self.i0lblRechargeCard.setFont(font)
        self.i0lblRechargeCard.setWordWrap(True)
        self.i0frQuit = QFrame(self.i0mainPage)
        self.i0frQuit.setObjectName(u"i0frQuit")
        self.i0frQuit.setGeometry(QRect(0, 530, 471, 241))
        self.i0frQuit.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}")
        self.i0frQuit.setFrameShape(QFrame.NoFrame)
        self.i0frQuit.setFrameShadow(QFrame.Plain)
        self.i0btnQuit = QPushButton(self.i0frQuit)
        self.i0btnQuit.setObjectName(u"i0btnQuit")
        self.i0btnQuit.setGeometry(QRect(10, 10, 160, 160))
        font2 = QFont()
        font2.setFamily(u"Berlin Sans FB")
        font2.setPointSize(48)
        font2.setBold(False)
        font2.setWeight(50)
        self.i0btnQuit.setFont(font2)
        self.i0btnQuit.setFocusPolicy(Qt.NoFocus)
        self.i0btnQuit.setAutoRepeat(False)
        self.i0btnQuit.setFlat(True)
        self.i0lblQuit = QLabel(self.i0frQuit)
        self.i0lblQuit.setObjectName(u"i0lblQuit")
        self.i0lblQuit.setGeometry(QRect(180, 50, 281, 81))
        font3 = QFont()
        font3.setFamily(u"Liberation Sans Narrow")
        font3.setPointSize(28)
        font3.setBold(True)
        font3.setWeight(75)
        self.i0lblQuit.setFont(font3)
        self.i0lblQuit.setWordWrap(True)
        self.i0frWelcome = QFrame(self.i0mainPage)
        self.i0frWelcome.setObjectName(u"i0frWelcome")
        self.i0frWelcome.setGeometry(QRect(370, 0, 661, 771))
        self.i0frWelcome.setMinimumSize(QSize(661, 771))
        self.i0frWelcome.setMaximumSize(QSize(661, 771))
        self.i0frWelcome.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}")
        self.i0frWelcome.setFrameShape(QFrame.NoFrame)
        self.i0frWelcome.setFrameShadow(QFrame.Plain)
        self.i0lblLogo = QLabel(self.i0frWelcome)
        self.i0lblLogo.setObjectName(u"i0lblLogo")
        self.i0lblLogo.setGeometry(QRect(50, 10, 141, 31))
        self.i0lblLogo.setPixmap(QPixmap(u":/bckgrnd/Logo_mobivend.png"))
        self.i0lblLogo.setScaledContents(True)
        self.i0lblWelcome = QLabel(self.i0frWelcome)
        self.i0lblWelcome.setObjectName(u"i0lblWelcome")
        self.i0lblWelcome.setGeometry(QRect(170, 150, 471, 351))
        self.i0lblWelcome.setMinimumSize(QSize(471, 351))
        self.i0lblWelcome.setMaximumSize(QSize(471, 351))
        font4 = QFont()
        font4.setFamily(u"Berlin Sans FB")
        font4.setPointSize(72)
        font4.setBold(False)
        font4.setWeight(50)
        self.i0lblWelcome.setFont(font4)
        self.i0lblWelcome.setWordWrap(True)
        self.i0lblAnimated = QLabel(self.i0frWelcome)
        self.i0lblAnimated.setObjectName(u"i0lblAnimated")
        self.i0lblAnimated.setGeometry(QRect(220, 490, 311, 261))
        self.i0frCardBalance = QFrame(self.i0frWelcome)
        self.i0frCardBalance.setObjectName(u"i0frCardBalance")
        self.i0frCardBalance.setGeometry(QRect(220, 20, 431, 161))
        self.i0frCardBalance.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}")
        self.i0frCardBalance.setFrameShape(QFrame.NoFrame)
        self.i0frCardBalance.setFrameShadow(QFrame.Plain)
        self.i0btnCardBalance = QPushButton(self.i0frCardBalance)
        self.i0btnCardBalance.setObjectName(u"i0btnCardBalance")
        self.i0btnCardBalance.setGeometry(QRect(270, 0, 160, 160))
        self.i0btnCardBalance.setFont(font1)
        self.i0btnCardBalance.setFocusPolicy(Qt.NoFocus)
        self.i0btnCardBalance.setAutoRepeat(False)
        self.i0btnCardBalance.setFlat(True)
        self.i0lblCardBalance = QLabel(self.i0frCardBalance)
        self.i0lblCardBalance.setObjectName(u"i0lblCardBalance")
        self.i0lblCardBalance.setGeometry(QRect(10, 40, 261, 81))
        self.i0lblCardBalance.setFont(font)
        self.i0lblCardBalance.setWordWrap(True)
        self.stackedWidget.addWidget(self.i0mainPage)
        self.i0frWelcome.raise_()
        self.i0frGetCoins.raise_()
        self.i0frNewCard.raise_()
        self.i0frRechargeCard.raise_()
        self.i0frQuit.raise_()
        self.i1pageInsertNotes = QWidget()
        self.i1pageInsertNotes.setObjectName(u"i1pageInsertNotes")
        self.i1frNext = QFrame(self.i1pageInsertNotes)
        self.i1frNext.setObjectName(u"i1frNext")
        self.i1frNext.setGeometry(QRect(0, 0, 1025, 768))
        self.i1frNext.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}\n"
"\n"
"")
        self.i1frNext.setFrameShape(QFrame.NoFrame)
        self.i1frNext.setFrameShadow(QFrame.Plain)
        self.i1lblPleaseInsert = QLabel(self.i1frNext)
        self.i1lblPleaseInsert.setObjectName(u"i1lblPleaseInsert")
        self.i1lblPleaseInsert.setGeometry(QRect(500, 90, 521, 191))
        self.i1lblPleaseInsert.setFont(font2)
        self.i1lblPleaseInsert.setWordWrap(True)
        self.i1frBack = QFrame(self.i1frNext)
        self.i1frBack.setObjectName(u"i1frBack")
        self.i1frBack.setGeometry(QRect(0, 0, 471, 768))
        self.i1frBack.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}")
        self.i1frBack.setFrameShape(QFrame.NoFrame)
        self.i1frBack.setFrameShadow(QFrame.Plain)
        self.i1btnBack = QPushButton(self.i1frBack)
        self.i1btnBack.setObjectName(u"i1btnBack")
        self.i1btnBack.setGeometry(QRect(0, 570, 160, 160))
        self.i1btnBack.setFont(font2)
        self.i1btnBack.setFocusPolicy(Qt.NoFocus)
        self.i1btnBack.setAutoRepeat(False)
        self.i1btnBack.setFlat(True)
        self.i1lblBack = QLabel(self.i1frBack)
        self.i1lblBack.setObjectName(u"i1lblBack")
        self.i1lblBack.setGeometry(QRect(170, 610, 281, 81))
        self.i1lblBack.setFont(font)
        self.i1lblBack.setWordWrap(True)
        self.i1lblHelpMsg1 = QLabel(self.i1frBack)
        self.i1lblHelpMsg1.setObjectName(u"i1lblHelpMsg1")
        self.i1lblHelpMsg1.setGeometry(QRect(30, 20, 421, 281))
        self.i1lblHelpMsg1.setFont(font)
        self.i1lblHelpMsg1.setWordWrap(True)
        self.i1lblHelpMsg2 = QLabel(self.i1frBack)
        self.i1lblHelpMsg2.setObjectName(u"i1lblHelpMsg2")
        self.i1lblHelpMsg2.setGeometry(QRect(30, 310, 421, 241))
        self.i1lblHelpMsg2.setFont(font)
        self.i1lblHelpMsg2.setWordWrap(True)
        self.i1lblYourBalance = QLabel(self.i1frNext)
        self.i1lblYourBalance.setObjectName(u"i1lblYourBalance")
        self.i1lblYourBalance.setGeometry(QRect(500, 290, 371, 101))
        self.i1lblYourBalance.setFont(font2)
        self.i1lblYourBalance.setWordWrap(True)
        self.i1currentBalance = QLCDNumber(self.i1frNext)
        self.i1currentBalance.setObjectName(u"i1currentBalance")
        self.i1currentBalance.setGeometry(QRect(490, 400, 371, 111))
        self.i1currentBalance.setSmallDecimalPoint(False)
        self.i1currentBalance.setDigitCount(8)
        self.i1currentBalance.setProperty("value", 150.000000000000000)
        self.i1currentBalance.setProperty("intValue", 150)
        self.i1lblCurrency = QLabel(self.i1frNext)
        self.i1lblCurrency.setObjectName(u"i1lblCurrency")
        self.i1lblCurrency.setGeometry(QRect(880, 420, 141, 101))
        self.i1lblCurrency.setFont(font2)
        self.i1lblCurrency.setWordWrap(True)
        self.i1btnNext = QPushButton(self.i1frNext)
        self.i1btnNext.setObjectName(u"i1btnNext")
        self.i1btnNext.setGeometry(QRect(850, 570, 160, 160))
        self.i1btnNext.setFont(font)
        self.i1btnNext.setFocusPolicy(Qt.NoFocus)
        self.i1btnNext.setFlat(True)
        self.stackedWidget.addWidget(self.i1pageInsertNotes)
        self.i2pageFlexExchange = QWidget()
        self.i2pageFlexExchange.setObjectName(u"i2pageFlexExchange")
        self.i2frExAddBalance = QFrame(self.i2pageFlexExchange)
        self.i2frExAddBalance.setObjectName(u"i2frExAddBalance")
        self.i2frExAddBalance.setGeometry(QRect(0, 0, 1024, 768))
        self.i2frExAddBalance.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"")
        self.i2frExAddBalance.setFrameShape(QFrame.NoFrame)
        self.i2frExAddBalance.setFrameShadow(QFrame.Plain)
        self.i2lblPleaseAdjust = QLabel(self.i2frExAddBalance)
        self.i2lblPleaseAdjust.setObjectName(u"i2lblPleaseAdjust")
        self.i2lblPleaseAdjust.setGeometry(QRect(390, 80, 281, 191))
        font5 = QFont()
        font5.setFamily(u"Berlin Sans FB")
        font5.setPointSize(36)
        font5.setBold(False)
        font5.setWeight(50)
        self.i2lblPleaseAdjust.setFont(font5)
        self.i2lblPleaseAdjust.setWordWrap(True)
        self.i2frExSubBalance = QFrame(self.i2frExAddBalance)
        self.i2frExSubBalance.setObjectName(u"i2frExSubBalance")
        self.i2frExSubBalance.setGeometry(QRect(0, 0, 301, 768))
        self.i2frExSubBalance.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"")
        self.i2frExSubBalance.setFrameShape(QFrame.NoFrame)
        self.i2frExSubBalance.setFrameShadow(QFrame.Plain)
        self.i2btnExBack = QPushButton(self.i2frExSubBalance)
        self.i2btnExBack.setObjectName(u"i2btnExBack")
        self.i2btnExBack.setGeometry(QRect(0, 570, 160, 160))
        self.i2btnExBack.setFont(font2)
        self.i2btnExBack.setFocusPolicy(Qt.NoFocus)
        self.i2btnExBack.setFlat(True)
        self.i2lblBack = QLabel(self.i2frExSubBalance)
        self.i2lblBack.setObjectName(u"i2lblBack")
        self.i2lblBack.setGeometry(QRect(170, 610, 101, 81))
        self.i2lblBack.setFont(font)
        self.i2lblBack.setWordWrap(True)
        self.i2btnExSub100 = QPushButton(self.i2frExSubBalance)
        self.i2btnExSub100.setObjectName(u"i2btnExSub100")
        self.i2btnExSub100.setGeometry(QRect(0, 10, 160, 160))
        self.i2btnExSub100.setFont(font5)
        self.i2btnExSub100.setFocusPolicy(Qt.NoFocus)
        self.i2btnExSub100.setFlat(True)
        self.i2btnExSub10 = QPushButton(self.i2frExSubBalance)
        self.i2btnExSub10.setObjectName(u"i2btnExSub10")
        self.i2btnExSub10.setGeometry(QRect(0, 180, 160, 160))
        self.i2btnExSub10.setFont(font5)
        self.i2btnExSub10.setFocusPolicy(Qt.NoFocus)
        self.i2btnExSub10.setFlat(True)
        self.i2lblYouDeposited = QLabel(self.i2frExAddBalance)
        self.i2lblYouDeposited.setObjectName(u"i2lblYouDeposited")
        self.i2lblYouDeposited.setGeometry(QRect(390, 410, 371, 101))
        self.i2lblYouDeposited.setFont(font5)
        self.i2lblYouDeposited.setWordWrap(True)
        self.i2exchangeBalance = QLCDNumber(self.i2frExAddBalance)
        self.i2exchangeBalance.setObjectName(u"i2exchangeBalance")
        self.i2exchangeBalance.setGeometry(QRect(360, 270, 251, 71))
        self.i2exchangeBalance.setSmallDecimalPoint(False)
        self.i2exchangeBalance.setDigitCount(8)
        self.i2exchangeBalance.setProperty("value", 150.000000000000000)
        self.i2exchangeBalance.setProperty("intValue", 150)
        self.i2lblExCurrency1 = QLabel(self.i2frExAddBalance)
        self.i2lblExCurrency1.setObjectName(u"i2lblExCurrency1")
        self.i2lblExCurrency1.setGeometry(QRect(620, 260, 101, 101))
        self.i2lblExCurrency1.setFont(font5)
        self.i2lblExCurrency1.setWordWrap(True)
        self.i2btnExDone = QPushButton(self.i2frExAddBalance)
        self.i2btnExDone.setObjectName(u"i2btnExDone")
        self.i2btnExDone.setGeometry(QRect(850, 570, 160, 160))
        self.i2btnExDone.setFont(font)
        self.i2btnExDone.setFocusPolicy(Qt.NoFocus)
        self.i2btnExDone.setFlat(True)
        self.i2btnExAdd100 = QPushButton(self.i2frExAddBalance)
        self.i2btnExAdd100.setObjectName(u"i2btnExAdd100")
        self.i2btnExAdd100.setGeometry(QRect(860, 10, 160, 160))
        self.i2btnExAdd100.setFont(font5)
        self.i2btnExAdd100.setFocusPolicy(Qt.NoFocus)
        self.i2btnExAdd100.setFlat(True)
        self.i2btnExAdd10 = QPushButton(self.i2frExAddBalance)
        self.i2btnExAdd10.setObjectName(u"i2btnExAdd10")
        self.i2btnExAdd10.setGeometry(QRect(860, 170, 160, 160))
        self.i2btnExAdd10.setFont(font5)
        self.i2btnExAdd10.setFocusPolicy(Qt.NoFocus)
        self.i2btnExAdd10.setFlat(True)
        self.i2lblCurBalance = QLabel(self.i2frExAddBalance)
        self.i2lblCurBalance.setObjectName(u"i2lblCurBalance")
        self.i2lblCurBalance.setGeometry(QRect(340, 490, 261, 101))
        self.i2lblCurBalance.setFont(font2)
        self.i2lblCurBalance.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.i2lblCurBalance.setWordWrap(True)
        self.i2lblExCurrency2 = QLabel(self.i2frExAddBalance)
        self.i2lblExCurrency2.setObjectName(u"i2lblExCurrency2")
        self.i2lblExCurrency2.setGeometry(QRect(620, 500, 101, 101))
        self.i2lblExCurrency2.setFont(font5)
        self.i2lblExCurrency2.setWordWrap(True)
        self.stackedWidget.addWidget(self.i2pageFlexExchange)
        self.i3pageTxnStatus = QWidget()
        self.i3pageTxnStatus.setObjectName(u"i3pageTxnStatus")
        self.i3frTxnStatus = QFrame(self.i3pageTxnStatus)
        self.i3frTxnStatus.setObjectName(u"i3frTxnStatus")
        self.i3frTxnStatus.setGeometry(QRect(0, 0, 1024, 768))
        self.i3frTxnStatus.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}\n"
"")
        self.i3frTxnStatus.setFrameShape(QFrame.StyledPanel)
        self.i3frTxnStatus.setFrameShadow(QFrame.Raised)
        self.i3lblTxnStatusMsg1 = QLabel(self.i3frTxnStatus)
        self.i3lblTxnStatusMsg1.setObjectName(u"i3lblTxnStatusMsg1")
        self.i3lblTxnStatusMsg1.setGeometry(QRect(460, 20, 421, 281))
        self.i3lblTxnStatusMsg1.setFont(font)
        self.i3lblTxnStatusMsg1.setWordWrap(True)
        self.i3lblTxnStatusMsg2 = QLabel(self.i3frTxnStatus)
        self.i3lblTxnStatusMsg2.setObjectName(u"i3lblTxnStatusMsg2")
        self.i3lblTxnStatusMsg2.setGeometry(QRect(460, 300, 421, 241))
        self.i3lblTxnStatusMsg2.setFont(font)
        self.i3lblTxnStatusMsg2.setWordWrap(True)
        self.i3btnDismiss = QPushButton(self.i3frTxnStatus)
        self.i3btnDismiss.setObjectName(u"i3btnDismiss")
        self.i3btnDismiss.setGeometry(QRect(850, 550, 160, 160))
        self.i3btnDismiss.setFont(font2)
        self.i3btnDismiss.setFocusPolicy(Qt.NoFocus)
        self.i3btnDismiss.setAutoRepeat(False)
        self.i3btnDismiss.setFlat(True)
        self.i3lblDismiss = QLabel(self.i3frTxnStatus)
        self.i3lblDismiss.setObjectName(u"i3lblDismiss")
        self.i3lblDismiss.setGeometry(QRect(490, 550, 351, 161))
        self.i3lblDismiss.setFont(font)
        self.i3lblDismiss.setWordWrap(True)
        self.i3lblTxnStatusIcon = QLabel(self.i3frTxnStatus)
        self.i3lblTxnStatusIcon.setObjectName(u"i3lblTxnStatusIcon")
        self.i3lblTxnStatusIcon.setGeometry(QRect(50, 20, 311, 261))
        self.i3lblTxnStatusIcon.setPixmap(QPixmap(u":/bckgrnd/icn200approved.png"))
        self.i3lblTxnQRcode = QLabel(self.i3frTxnStatus)
        self.i3lblTxnQRcode.setObjectName(u"i3lblTxnQRcode")
        self.i3lblTxnQRcode.setGeometry(QRect(30, 360, 384, 384))
        self.i3lblTxnQRcode.setPixmap(QPixmap(u":/bckgrnd/qrcode-placeholder.png"))
        self.i3lblTxnQRcode.setScaledContents(True)
        self.stackedWidget.addWidget(self.i3pageTxnStatus)
        self.i4pageFixedExchange = QWidget()
        self.i4pageFixedExchange.setObjectName(u"i4pageFixedExchange")
        self.i4frFixedExchange = QFrame(self.i4pageFixedExchange)
        self.i4frFixedExchange.setObjectName(u"i4frFixedExchange")
        self.i4frFixedExchange.setGeometry(QRect(0, 0, 1024, 768))
        self.i4frFixedExchange.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}\n"
"")
        self.i4frFixedExchange.setFrameShape(QFrame.StyledPanel)
        self.i4frFixedExchange.setFrameShadow(QFrame.Raised)
        self.i4btnExChoice2 = QPushButton(self.i4frFixedExchange)
        self.i4btnExChoice2.setObjectName(u"i4btnExChoice2")
        self.i4btnExChoice2.setGeometry(QRect(840, 220, 160, 160))
        self.i4btnExChoice2.setFont(font5)
        self.i4btnExChoice2.setFocusPolicy(Qt.NoFocus)
        self.i4btnExChoice2.setFlat(True)
        self.i4lblYouDeposited = QLabel(self.i4frFixedExchange)
        self.i4lblYouDeposited.setObjectName(u"i4lblYouDeposited")
        self.i4lblYouDeposited.setGeometry(QRect(390, 400, 371, 101))
        self.i4lblYouDeposited.setFont(font5)
        self.i4lblYouDeposited.setWordWrap(True)
        self.i4btnExChoice1 = QPushButton(self.i4frFixedExchange)
        self.i4btnExChoice1.setObjectName(u"i4btnExChoice1")
        self.i4btnExChoice1.setGeometry(QRect(840, 40, 160, 160))
        self.i4btnExChoice1.setFont(font5)
        self.i4btnExChoice1.setFocusPolicy(Qt.NoFocus)
        self.i4btnExChoice1.setFlat(True)
        self.i4lblBack = QLabel(self.i4frFixedExchange)
        self.i4lblBack.setObjectName(u"i4lblBack")
        self.i4lblBack.setGeometry(QRect(170, 600, 101, 81))
        self.i4lblBack.setFont(font)
        self.i4lblBack.setWordWrap(True)
        self.i4lblCurBalance = QLabel(self.i4frFixedExchange)
        self.i4lblCurBalance.setObjectName(u"i4lblCurBalance")
        self.i4lblCurBalance.setGeometry(QRect(340, 480, 261, 101))
        self.i4lblCurBalance.setFont(font2)
        self.i4lblCurBalance.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.i4lblCurBalance.setWordWrap(True)
        self.i4lblExCurrency = QLabel(self.i4frFixedExchange)
        self.i4lblExCurrency.setObjectName(u"i4lblExCurrency")
        self.i4lblExCurrency.setGeometry(QRect(620, 490, 101, 101))
        self.i4lblExCurrency.setFont(font5)
        self.i4lblExCurrency.setWordWrap(True)
        self.i4btnExBack = QPushButton(self.i4frFixedExchange)
        self.i4btnExBack.setObjectName(u"i4btnExBack")
        self.i4btnExBack.setGeometry(QRect(0, 560, 160, 160))
        self.i4btnExBack.setFont(font2)
        self.i4btnExBack.setFocusPolicy(Qt.NoFocus)
        self.i4btnExBack.setFlat(True)
        self.i4lblPleaseChoose = QLabel(self.i4frFixedExchange)
        self.i4lblPleaseChoose.setObjectName(u"i4lblPleaseChoose")
        self.i4lblPleaseChoose.setGeometry(QRect(390, 60, 411, 251))
        self.i4lblPleaseChoose.setFont(font5)
        self.i4lblPleaseChoose.setWordWrap(True)
        self.stackedWidget.addWidget(self.i4pageFixedExchange)
        self.i5pageCardInteract = QWidget()
        self.i5pageCardInteract.setObjectName(u"i5pageCardInteract")
        self.i5frCardInteract = QFrame(self.i5pageCardInteract)
        self.i5frCardInteract.setObjectName(u"i5frCardInteract")
        self.i5frCardInteract.setGeometry(QRect(0, 0, 1024, 768))
        self.i5frCardInteract.setStyleSheet(u"QPushButton{ border-image: url(:/buttons/btn500.png);}\n"
"QPushButton:pressed {border-image: url(:/buttons/btn500pressed.png); border: none;}\n"
"QPushButton:disabled {border-image: url(:/bckgrnd/bgnd500.png); border: none;}\n"
"")
        self.i5frCardInteract.setFrameShape(QFrame.StyledPanel)
        self.i5frCardInteract.setFrameShadow(QFrame.Raised)
        self.i5btnDismiss = QPushButton(self.i5frCardInteract)
        self.i5btnDismiss.setObjectName(u"i5btnDismiss")
        self.i5btnDismiss.setGeometry(QRect(820, 530, 160, 160))
        self.i5btnDismiss.setFont(font2)
        self.i5btnDismiss.setFocusPolicy(Qt.NoFocus)
        self.i5btnDismiss.setAutoRepeat(False)
        self.i5btnDismiss.setFlat(True)
        self.i5lblCardMsg2 = QLabel(self.i5frCardInteract)
        self.i5lblCardMsg2.setObjectName(u"i5lblCardMsg2")
        self.i5lblCardMsg2.setGeometry(QRect(430, 280, 421, 241))
        self.i5lblCardMsg2.setFont(font)
        self.i5lblCardMsg2.setWordWrap(True)
        self.i5lblDismiss = QLabel(self.i5frCardInteract)
        self.i5lblDismiss.setObjectName(u"i5lblDismiss")
        self.i5lblDismiss.setGeometry(QRect(460, 530, 351, 161))
        self.i5lblDismiss.setFont(font)
        self.i5lblDismiss.setWordWrap(True)
        self.i5lblCardIcon = QLabel(self.i5frCardInteract)
        self.i5lblCardIcon.setObjectName(u"i5lblCardIcon")
        self.i5lblCardIcon.setGeometry(QRect(20, 0, 311, 261))
        self.i5lblCardIcon.setPixmap(QPixmap(u":/bckgrnd/icn200approved.png"))
        self.i5lblCardMsg1 = QLabel(self.i5frCardInteract)
        self.i5lblCardMsg1.setObjectName(u"i5lblCardMsg1")
        self.i5lblCardMsg1.setGeometry(QRect(430, 0, 421, 281))
        self.i5lblCardMsg1.setFont(font)
        self.i5lblCardMsg1.setWordWrap(True)
        self.stackedWidget.addWidget(self.i5pageCardInteract)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.i0btnGetCoins.setText("")
#if QT_CONFIG(shortcut)
        self.i0btnGetCoins.setShortcut(QCoreApplication.translate("MainWindow", u"G", None))
#endif // QT_CONFIG(shortcut)
        self.i0lblGetCoins.setText(QCoreApplication.translate("MainWindow", u"Get Coins for Notes", None))
        self.i0btnNewCard.setText(QCoreApplication.translate("MainWindow", u"New\n"
"Card", None))
#if QT_CONFIG(shortcut)
        self.i0btnNewCard.setShortcut(QCoreApplication.translate("MainWindow", u"B", None))
#endif // QT_CONFIG(shortcut)
        self.i0lblNewCard.setText(QCoreApplication.translate("MainWindow", u"Buy a NEW Vendotek Card", None))
        self.i0btnRechargeCard.setText("")
#if QT_CONFIG(shortcut)
        self.i0btnRechargeCard.setShortcut(QCoreApplication.translate("MainWindow", u"R", None))
#endif // QT_CONFIG(shortcut)
        self.i0lblRechargeCard.setText(QCoreApplication.translate("MainWindow", u"Recharge Your Vendotek Card", None))
        self.i0btnQuit.setText(QCoreApplication.translate("MainWindow", u"Q", None))
#if QT_CONFIG(shortcut)
        self.i0btnQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.i0lblQuit.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u043e\u043b\u0438\u0446\u0446\u043e", None))
        self.i0lblLogo.setText("")
        self.i0lblWelcome.setText(QCoreApplication.translate("MainWindow", u"V\u00edtejte Nov\u00fd Z\u00e1kazn\u00edk!", None))
        self.i0lblAnimated.setText("")
        self.i0btnCardBalance.setText(QCoreApplication.translate("MainWindow", u"Card\n"
"Balance", None))
#if QT_CONFIG(shortcut)
        self.i0btnCardBalance.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.i0lblCardBalance.setText(QCoreApplication.translate("MainWindow", u"Check Balance\n"
"on Your Account", None))
        self.i1lblPleaseInsert.setText(QCoreApplication.translate("MainWindow", u"Please Insert Notes", None))
        self.i1btnBack.setText(QCoreApplication.translate("MainWindow", u"Q", None))
#if QT_CONFIG(shortcut)
        self.i1btnBack.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.i1lblBack.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.i1lblHelpMsg1.setText(QCoreApplication.translate("MainWindow", u"Help Message 1", None))
        self.i1lblHelpMsg2.setText(QCoreApplication.translate("MainWindow", u"Help Message 2", None))
        self.i1lblYourBalance.setText(QCoreApplication.translate("MainWindow", u"Your Balance", None))
        self.i1lblCurrency.setText(QCoreApplication.translate("MainWindow", u"CZK", None))
        self.i1btnNext.setText(QCoreApplication.translate("MainWindow", u"Next", None))
#if QT_CONFIG(shortcut)
        self.i1btnNext.setShortcut(QCoreApplication.translate("MainWindow", u"N", None))
#endif // QT_CONFIG(shortcut)
        self.i2lblPleaseAdjust.setText(QCoreApplication.translate("MainWindow", u"Please Adjust Amount for Exchange", None))
        self.i2btnExBack.setText(QCoreApplication.translate("MainWindow", u"Q", None))
#if QT_CONFIG(shortcut)
        self.i2btnExBack.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.i2lblBack.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.i2btnExSub100.setText(QCoreApplication.translate("MainWindow", u"-100", None))
        self.i2btnExSub10.setText(QCoreApplication.translate("MainWindow", u"-10", None))
        self.i2lblYouDeposited.setText(QCoreApplication.translate("MainWindow", u"You Deposited", None))
        self.i2lblExCurrency1.setText(QCoreApplication.translate("MainWindow", u"CZK", None))
        self.i2btnExDone.setText(QCoreApplication.translate("MainWindow", u"Done", None))
#if QT_CONFIG(shortcut)
        self.i2btnExDone.setShortcut(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(shortcut)
        self.i2btnExAdd100.setText(QCoreApplication.translate("MainWindow", u"+100", None))
#if QT_CONFIG(shortcut)
        self.i2btnExAdd100.setShortcut(QCoreApplication.translate("MainWindow", u"N", None))
#endif // QT_CONFIG(shortcut)
        self.i2btnExAdd10.setText(QCoreApplication.translate("MainWindow", u"+10", None))
#if QT_CONFIG(shortcut)
        self.i2btnExAdd10.setShortcut(QCoreApplication.translate("MainWindow", u"N", None))
#endif // QT_CONFIG(shortcut)
        self.i2lblCurBalance.setText(QCoreApplication.translate("MainWindow", u"999", None))
        self.i2lblExCurrency2.setText(QCoreApplication.translate("MainWindow", u"CZK", None))
        self.i3lblTxnStatusMsg1.setText(QCoreApplication.translate("MainWindow", u"Help Message 1", None))
        self.i3lblTxnStatusMsg2.setText(QCoreApplication.translate("MainWindow", u"Help Message 2", None))
        self.i3btnDismiss.setText(QCoreApplication.translate("MainWindow", u"OK", None))
#if QT_CONFIG(shortcut)
        self.i3btnDismiss.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.i3lblDismiss.setText(QCoreApplication.translate("MainWindow", u"Dismiss/Next Customer", None))
        self.i3lblTxnStatusIcon.setText("")
        self.i3lblTxnQRcode.setText("")
        self.i4btnExChoice2.setText(QCoreApplication.translate("MainWindow", u"400", None))
        self.i4lblYouDeposited.setText(QCoreApplication.translate("MainWindow", u"You Deposited", None))
        self.i4btnExChoice1.setText(QCoreApplication.translate("MainWindow", u"200", None))
        self.i4lblBack.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.i4lblCurBalance.setText(QCoreApplication.translate("MainWindow", u"999", None))
        self.i4lblExCurrency.setText(QCoreApplication.translate("MainWindow", u"CZK", None))
        self.i4btnExBack.setText(QCoreApplication.translate("MainWindow", u"Q", None))
#if QT_CONFIG(shortcut)
        self.i4btnExBack.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.i4lblPleaseChoose.setText(QCoreApplication.translate("MainWindow", u"Please Adjust Coin Amount for Exchange", None))
        self.i5btnDismiss.setText(QCoreApplication.translate("MainWindow", u"OK", None))
#if QT_CONFIG(shortcut)
        self.i5btnDismiss.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.i5lblCardMsg2.setText(QCoreApplication.translate("MainWindow", u"Another Help Message", None))
        self.i5lblDismiss.setText(QCoreApplication.translate("MainWindow", u"Dismiss/Cancel", None))
        self.i5lblCardIcon.setText("")
        self.i5lblCardMsg1.setText(QCoreApplication.translate("MainWindow", u"Present/Remove your Card", None))
    # retranslateUi

